"""Generated by scripts/gen_models.py from schemas/design.schema.json. Do not edit; change the schema and regenerate."""

from __future__ import annotations

from typing import Annotated, Any, ClassVar, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, model_validator


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")
    __non_nullable__: ClassVar[tuple[str, ...]] = ()

    @model_validator(mode="before")
    @classmethod
    def _reject_explicit_null(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for key in cls.__non_nullable__:
                if key in data and data[key] is None:
                    raise ValueError(f"{key}: null is not allowed; omit the field instead")
        return data


Ulid = Annotated[str, Field(pattern='^[0-7][0-9A-HJKMNP-TV-Z]{25}$')]
Ref = Union[float, str]


class AssetRef(_Strict):
    """Reference to another asset: id, optionally pinned to a version or content hash"""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('version', 'hash', )

    id: Ulid = Field(...)
    version: Union[int, None] = Field(default=None, ge=1, description='Version of the referenced asset (optional)')
    hash: Union[str, None] = Field(default=None, pattern='^sha256:[0-9a-f]{64}$', description='Content hash of the referenced asset (optional, for immutable artifacts)')


class Crank(_Strict):
    """Crank"""

    x: Ref = Field(...)
    y: Ref = Field(...)
    length: Ref = Field(...)


class Joint(_Strict):
    """A joint solved as the intersection of two circles"""

    id: str = Field(..., min_length=1, description='Joint id')
    centers: list[str] = Field(..., min_length=2, max_length=2, description='Ids of the two points the circles are centred on')
    radii: list[Ref] = Field(..., min_length=2, max_length=2, description='Radii of the two circles (link lengths)')
    side: Literal[1, -1] = Field(..., description='Which of the two intersections; fixes the assembly branch')


class Linkage(_Strict):
    """A LinkageSpec: named lengths, crank, and joints defined as circle intersections"""

    params: dict[str, float] = Field(..., min_length=1, description='Named link lengths')
    crank: Crank = Field(...)
    joints: list[Joint] = Field(..., min_length=1, description='Joints in solving order')
    foot: str = Field(..., description='Id of the joint that is the foot')


class Walker(_Strict):
    """Walker"""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('lateral_spacing_m', 'body_length_m', )

    legs: int = Field(..., ge=1, description='Number of legs')
    unit_m: float = Field(..., gt=0, description='Metres per length unit of the linkage')
    direction: Literal[-1, 1] = Field(..., description='Crank turning sense that walks the leg forward')
    body_mass_kg: float = Field(..., gt=0, description='Frame, motor and payload; excludes the legs')
    lateral_spacing_m: Union[float, None] = Field(default=None, ge=0, description='Distance between neighbouring legs')
    body_length_m: Union[float, None] = Field(default=None, gt=0, description='Torso length (sets pitch inertia only)')


class Sail(_Strict):
    """Sail drive parameters"""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('area_m2', 'radius_m', 'drag_coeff', 'gear', 'inertia_kg_m2', 'damping_nm_s', 'friction_nm', )

    area_m2: Union[float, None] = Field(default=None, gt=0, description='Sail area')
    radius_m: Union[float, None] = Field(default=None, gt=0, description='Lever arm of the sail')
    drag_coeff: Union[float, None] = Field(default=None, gt=0, description='Drag coefficient')
    gear: Union[float, None] = Field(default=None, gt=0, description='Sail turns per crank turn')
    inertia_kg_m2: Union[float, None] = Field(default=None, ge=0, description='Rotational inertia at the crank')
    damping_nm_s: Union[float, None] = Field(default=None, ge=0, description='Viscous loss')
    friction_nm: Union[float, None] = Field(default=None, ge=0, description='Coulomb friction')


class Drive(_Strict):
    """Drive"""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('motor_omega_rad_s', 'sail', )

    kind: Literal['motor', 'sail'] = Field(..., description='Drive kind')
    motor_omega_rad_s: Union[float, None] = Field(default=None, description='Motor speed')
    sail: Union[Sail, None] = None


class Motor(_Strict):
    """Small gear motor mounted behind a frame plate; a hole pattern assumption for N20-class motors"""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('shaft_diameter_mm', 'mount_hole_spacing_mm', 'mount_hole_diameter_mm', )

    shaft_diameter_mm: Union[float, None] = Field(default=None, gt=0, description='Output shaft diameter')
    mount_hole_spacing_mm: Union[float, None] = Field(default=None, gt=0, description='Mounting hole spacing')
    mount_hole_diameter_mm: Union[float, None] = Field(default=None, gt=0, description='Mounting hole diameter')


class Manufacturing(_Strict):
    """Manufacturing parameters"""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('layer_height_mm', 'min_wall_mm', 'bed_mm', 'press_fit_offset_mm', 'leg_gap_mm', 'motor', )

    process: Literal['fdm'] = Field(..., description='Manufacturing process')
    material: Literal['PLA', 'PETG'] = Field(..., description='Material')
    bar_width_mm: float = Field(..., gt=0, description='Bar width')
    bar_thickness_mm: float = Field(..., gt=0, description='Bar thickness')
    pin_diameter_mm: float = Field(..., gt=0, description='Nominal pin or bolt diameter')
    clearance_mm: float = Field(..., ge=0, description='Added to the hole diameter')
    layer_height_mm: Union[float, None] = Field(default=None, gt=0, description='Layer height')
    min_wall_mm: Union[float, None] = Field(default=None, gt=0, description='Minimum wall thickness')
    bed_mm: Union[list[Annotated[float, Field(gt=0)]], None] = Field(default=None, min_length=2, max_length=2, description='Print bed size [x, y]')
    press_fit_offset_mm: Union[float, None] = Field(default=None, description='Added to a shaft diameter for holes that must grip (negative = tighter); FDM holes print small, tune after a test print')
    leg_gap_mm: Union[float, None] = Field(default=None, ge=0, description='Clearance between neighbouring legs along the axles')
    motor: Union[Motor, None] = None


class Design(_Strict):
    """A walker: linkage geometry, scale, drive and manufacturing parameters. The single source for kinematics, evolution, simulation and fabrication."""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('parent', 'aliases', 'notes', )

    schema_version: Literal[2] = Field(...)
    id: Ulid = Field(...)
    name: str = Field(..., min_length=1, description='Design name (display only; may change)')
    parent: Union[AssetRef, None] = Field(default=None, description='The design this one was copied from (genealogy)')
    aliases: Union[list[str], None] = Field(default=None, description='Former names or ids; a reference to any of them resolves to this asset')
    notes: Union[str, None] = Field(default=None, description='Notes')
    linkage: Linkage = Field(...)
    walker: Walker = Field(...)
    drive: Drive = Field(...)
    manufacturing: Manufacturing = Field(...)
