"""Generated by scripts/gen_models.py from schemas/ops.schema.json. Do not edit; change the schema and regenerate."""

from __future__ import annotations

from typing import Annotated, Any, ClassVar, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, model_validator


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")
    __non_nullable__: ClassVar[tuple[str, ...]] = ()

    @model_validator(mode="before")
    @classmethod
    def _reject_explicit_null(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for key in cls.__non_nullable__:
                if key in data and data[key] is None:
                    raise ValueError(f"{key}: null is not allowed; omit the field instead")
        return data


Ulid = Annotated[str, Field(pattern='^[0-7][0-9A-HJKMNP-TV-Z]{25}$')]
Ref = Union[float, str]


class Actor(_Strict):
    """Who made the change"""

    kind: Literal['human', 'algorithm', 'agent'] = Field(..., description='A person, an algorithm (genetic algorithm, optimiser) or an agent')
    id: str = Field(..., description='Identifier of the actor (user name, algorithm name, agent name)')


class SetParamArgs(_Strict):
    """Set one named length"""

    name: str = Field(..., min_length=1, description='Name of an entry in linkage.params')
    value: float = Field(..., description='New length')


class AddDyadArgs(_Strict):
    """Add a joint at the intersection of two circles"""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('params', 'foot', )

    id: str = Field(..., min_length=1, description='Id of the new joint (not an existing one, nor G, C, P)')
    centers: list[str] = Field(..., min_length=2, max_length=2, description='Ids of the two points the circles are centred on (already solved points)')
    radii: list[Ref] = Field(..., min_length=2, max_length=2, description='Radii of the two circles (bar lengths)')
    side: Literal[1, -1] = Field(..., description='Which of the two intersections')
    params: Union[dict[str, float], None] = Field(default=None, description='New named lengths created together with the joint')
    foot: Union[bool, None] = Field(default=None, description='If true the new joint becomes the foot')


class RemoveJointArgs(_Strict):
    """Remove a joint nothing else is built on"""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('foot', )

    id: str = Field(..., min_length=1, description='Joint to remove')
    foot: Union[str, None] = Field(default=None, description='The new foot, required when the removed joint is the foot')
    drop_params: bool = Field(default=True, description='Also delete named lengths only this joint used')


class SetLengthArgs(_Strict):
    """Set one length by handle"""

    key: str = Field(..., min_length=1, description='Length handle: the name of a named length, or crank.x, crank.y, crank.length, joint:ID.radii.N (a number written inline in the spec)')
    value: float = Field(..., description='New length')


class SetPropertyArgs(_Strict):
    """Set an existing editable property of the design"""

    path: str = Field(..., min_length=1, description='JSON pointer such as /walker/legs; editable roots: /name, /notes, /walker, /drive, /manufacturing')
    value: Any = Field(..., description='New value; it must keep the kind of the old value, ranges are enforced by the schema')


class ArrayLegsArgs(_Strict):
    """Set the number of legs"""

    legs: int = Field(..., ge=1, description='Number of legs')


class ScaleArgs(_Strict):
    """Multiply every length by a factor"""

    factor: float = Field(..., gt=0, description='Scale factor')
    keep_physical: bool = Field(default=False, description='If true the length unit changes too, so the physical size stays the same')


class MirrorArgs(_Strict):
    """Reflect the leg left to right and reverse the crank direction"""



class SetMaterialArgs(_Strict):
    """Choose the printing material"""

    material: Literal['PLA', 'PETG'] = Field(..., description='Material')


class PatchStep(_Strict):
    """One JSON patch step"""

    __non_nullable__: ClassVar[tuple[str, ...]] = ('value', )

    op: Literal['add', 'replace', 'remove'] = Field(..., description='Patch operation')
    path: str = Field(..., description='JSON pointer')
    value: Union[Any, None] = Field(default=None, description='New value (for add and replace)')


class PatchArgs(_Strict):
    """A list of JSON patch steps; what an undo contains"""

    patch: list[PatchStep] = Field(..., description='Patch steps')


class SetParamOp(_Strict):
    """Set a length"""

    id: Ulid = Field(...)
    type: Literal['set_param'] = Field(...)
    args: SetParamArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class SetLengthOp(_Strict):
    """Set a length by handle"""

    id: Ulid = Field(...)
    type: Literal['set_length'] = Field(...)
    args: SetLengthArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class SetPropertyOp(_Strict):
    """Set a property"""

    id: Ulid = Field(...)
    type: Literal['set_property'] = Field(...)
    args: SetPropertyArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class AddDyadOp(_Strict):
    """Add a dyad"""

    id: Ulid = Field(...)
    type: Literal['add_dyad'] = Field(...)
    args: AddDyadArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class RemoveJointOp(_Strict):
    """Remove a joint"""

    id: Ulid = Field(...)
    type: Literal['remove_joint'] = Field(...)
    args: RemoveJointArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class ArrayLegsOp(_Strict):
    """Set the leg count"""

    id: Ulid = Field(...)
    type: Literal['array_legs'] = Field(...)
    args: ArrayLegsArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class ScaleOp(_Strict):
    """Scale"""

    id: Ulid = Field(...)
    type: Literal['scale'] = Field(...)
    args: ScaleArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class MirrorOp(_Strict):
    """Mirror"""

    id: Ulid = Field(...)
    type: Literal['mirror'] = Field(...)
    args: MirrorArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class SetMaterialOp(_Strict):
    """Set the material"""

    id: Ulid = Field(...)
    type: Literal['set_material'] = Field(...)
    args: SetMaterialArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class PatchOp(_Strict):
    """Patch (the record of an undo)"""

    id: Ulid = Field(...)
    type: Literal['patch'] = Field(...)
    args: PatchArgs = Field(...)
    actor: Actor = Field(...)
    reason: str = Field(default='', description='Why the change was made (for people and agents)')
    time: str = Field(..., pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?Z$', description='When it happened (ISO 8601, UTC)')


class OpLog(_Strict):
    """The edit log of a design: the base design and the operations applied to it. The log is the source of truth; the current design is its fold."""

    schema_version: Literal[1] = Field(...)
    design_id: Ulid = Field(...)
    base: dict[str, Any] = Field(..., description='The initial design (conforms to the design schema)')
    ops: list[Operation] = Field(..., description='Operations in the order they were applied')


Operation = Union[SetParamOp, SetLengthOp, SetPropertyOp, AddDyadOp, RemoveJointOp, ArrayLegsOp, ScaleOp, MirrorOp, SetMaterialOp, PatchOp]
