"""Generated by scripts/gen_models.py from schemas/scenario.schema.json. Do not edit; change the schema and regenerate."""

from __future__ import annotations

from typing import Annotated, Any, ClassVar, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, model_validator


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")
    __non_nullable__: ClassVar[tuple[str, ...]] = ()

    @model_validator(mode="before")
    @classmethod
    def _reject_explicit_null(cls, data: Any) -> Any:
        if isinstance(data, dict):
            for key in cls.__non_nullable__:
                if key in data and data[key] is None:
                    raise ValueError(f"{key}: null is not allowed; omit the field instead")
        return data


class Linkage(_Strict):
    """Linkage"""

    spec: Union[str, dict[str, Any]] = Field(default='jansen', description='"jansen", "design", a path to a LinkageSpec JSON exported by packages/core, or an inline LinkageSpec object')
    params: dict[str, float] = Field(default_factory=dict, description='Overrides of named lengths, e.g. {"m": 16.0}')


class Walker(_Strict):
    """Walker"""

    legs: int = Field(default=12, ge=1, description='Number of legs')
    mass: float = Field(default=50.0, gt=0, description='Total mass (the torso gets what the bars do not); ignored if body_mass is set')
    body_mass: Union[float, None] = Field(default=None, gt=0, description='Torso mass; legs are added on top')
    unit: float = Field(default=0.02, gt=0, description='Metres per length unit of the linkage')
    direction: Literal[-1, 1] = Field(default=-1, description='Crank turning sense that walks the leg forward; -1 for the Jansen leg')
    tube_mass_per_m: float = Field(default=0.12, ge=0, description='Mass per metre of tube')
    min_bar_mass: float = Field(default=0.001, gt=0, description="Floor on a bar's mass")
    lateral_spacing: float = Field(default=0.1, ge=0, description='Distance between neighbouring legs (visual only)')
    body_length: float = Field(default=1.0, gt=0, description='Torso length; sets pitch inertia only')
    pitch: Literal['free', 'locked'] = Field(default='free', description="Torso pitch freedom; 'locked' removes tipping")
    bar_radius: float = Field(default=0.008, gt=0, description='Visual capsule radius of bars, no collisions')
    foot_radius: float = Field(default=0.01, gt=0, description='Foot sphere radius')
    foot_friction: float = Field(default=1.5, gt=0, description='Foot friction coefficient')


class Environment(_Strict):
    """Environment"""

    gravity: float = Field(default=9.81, ge=0, description='Gravitational acceleration')
    air_density: float = Field(default=1.2, ge=0, description='Air density; scales the sail torque')


class Wind(_Strict):
    """Wind"""

    kind: str = Field(default='constant', description='Wind kind: constant, gusts, ...')
    speed: float = Field(default=0.0, ge=0, description='Mean wind speed (the wind pushes the sail drive, not the body)')
    params: dict[str, Any] = Field(default_factory=dict, description='Kind-specific parameters, e.g. gusts {amplitude, period}')


class Terrain(_Strict):
    """Terrain"""

    kind: str = Field(default='flat', description='Terrain kind: flat, slope, step, bumps, ...')
    friction: float = Field(default=1.5, gt=0, description='Ground friction coefficient')
    slope_deg: float = Field(default=0.0, description='Slope angle (implemented by tilting gravity)')
    params: dict[str, Any] = Field(default_factory=dict, description='Kind-specific parameters')


class Drive(_Strict):
    """Drive"""

    kind: str = Field(default='motor', description='Drive kind: motor (position servo) or sail')
    omega: float = Field(default=0.3, description='Crank speed in the walking direction (motor drive)')
    kp: float = Field(default=5000.0, gt=0, description='Position-servo stiffness')
    max_torque: Union[float, None] = Field(default=None, gt=0, description='Motor torque limit; null = unlimited, only sensible for ideal prescribed motion. Without a limit a blocked foot forces the linkage open')
    kv: float = Field(default=500.0, gt=0, description='Servo damping')
    ramp: float = Field(default=2.0, ge=0, description='Time to ramp up to omega')
    sail_area: float = Field(default=0.03, gt=0, description='Sail area')
    sail_radius: float = Field(default=0.08, gt=0, description='Lever arm of the sail on its shaft')
    sail_drag_coeff: float = Field(default=1.2, gt=0, description='Sail drag coefficient')
    sail_gear: float = Field(default=10.0, gt=0, description='Sail turns per crank turn')
    rotor_inertia: float = Field(default=0.0001, ge=0, description='Rotational inertia at the crank')
    crank_damping: float = Field(default=0.001, ge=0, description='Viscous loss at the crank')
    crank_friction: float = Field(default=0.002, ge=0, description='Coulomb friction at the crank')
    params: dict[str, Any] = Field(default_factory=dict, description='Kind-specific parameters')


class Solver(_Strict):
    """Solver"""

    timestep: float = Field(default=0.00025, gt=0, description='Time step; peak torque needs <= 0.25 ms to converge (docs/EXPERIMENTS.md section 8)')
    iterations: int = Field(default=100, ge=1, description='Solver iterations')
    contact_solref: float = Field(default=0.02, gt=0, description='Foot/terrain contact time constant, used only when contact_stiffness is unset; depends on effective mass, so a numerical knob')
    contact_stiffness: Union[float, None] = Field(default=100000.0, gt=0, description="Contact stiffness in MuJoCo's mass-normalised units (1/s^2), NOT N/m: a foot sinks by about 0.64 mm * (1000 / k) per 1 g of load acceleration regardless of its mass. A calibration target. null = use contact_solref")
    contact_damping_ratio: float = Field(default=1.0, gt=0, description='Damping ratio used to derive contact damping from the stiffness')
    cone: Literal['pyramidal', 'elliptic'] = Field(default='pyramidal', description='Friction cone type')
    impratio: float = Field(default=1.0, ge=1, description='Friction-vs-normal constraint impedance ratio')
    noslip_iterations: int = Field(default=0, ge=0, description='Number of noslip post-processing iterations')
    solref_time: float = Field(default=0.002, gt=0, description='Constraint stiffness time constant (smaller = stiffer; keep >= 2*timestep)')
    solimp: str = Field(default='0.99 0.999 0.0001', description='Constraint impedance (MuJoCo solimp); near 1 = rigid joints')


class Run(_Strict):
    """Run"""

    settle: float = Field(default=1.0, ge=0, description='Seconds with the crank held before driving')
    revolutions: float = Field(default=3.0, gt=0, description='Crank revolutions')
    max_time: float = Field(default=600.0, gt=0, description='Maximum simulated time')
    record_every: int = Field(default=10, ge=1, description='Record time-series data every N steps')
    frame_rate: float = Field(default=30.0, ge=0, description='Replay frame rate; 0 = do not record')
    give_up_after: float = Field(default=0.0, ge=0, description='Stop as stalled if the crank has moved less than 0.1 rad by then (0 = never); for sail drives that may not start')


class Scenario(_Strict):
    """One document that fully determines a simulation run. Defaults marked x-assumption are guesses, not measurements."""

    schema_version: Literal[1] = 1
    name: str = Field(default='unnamed', description='Scenario name')
    linkage: Linkage = Field(default_factory=Linkage)
    walker: Walker = Field(default_factory=Walker)
    environment: Environment = Field(default_factory=Environment)
    wind: Wind = Field(default_factory=Wind)
    terrain: Terrain = Field(default_factory=Terrain)
    drive: Drive = Field(default_factory=Drive)
    solver: Solver = Field(default_factory=Solver)
    run: Run = Field(default_factory=Run)
