#!/usr/bin/env python3
"""Generate pydantic models (Python) and interfaces (TypeScript) from schemas/*.schema.json.

  python scripts/gen_models.py            # (re)write the generated files
  python scripts/gen_models.py --check    # fail if a generated file is out of date (CI)
  python scripts/gen_models.py --schemas DIR --py-out DIR --ts-out DIR   # alternative locations (tests)

The JSON Schema files are the source of truth (ADR-0007, E1-03). This generator supports the subset the repo uses
and fails loudly on anything else, so a schema change can never silently produce a wrong type:
  object (properties, required, additionalProperties false / true / schema, minProperties), array (items, minItems, maxItems),
  string / number / integer / boolean / null, type lists, enum, const, oneOf / anyOf, $ref to #/$defs/*,
  default, minimum / exclusiveMinimum / maximum / exclusiveMaximum, minLength, x-doc, x-unit, description.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = ("design", "scenario")
KNOWN = {
    "$schema", "$id", "$defs", "$ref", "title", "description", "type", "properties", "required", "additionalProperties",
    "minProperties", "items", "minItems", "maxItems", "enum", "const", "oneOf", "anyOf", "default", "minimum",
    "exclusiveMinimum", "maximum", "exclusiveMaximum", "minLength",
}
HEADER = "Generated by scripts/gen_models.py from schemas/{name}.schema.json. Do not edit; change the schema and regenerate."


def check_keywords(node: Any, where: str) -> None:
    if isinstance(node, dict):
        for k, v in node.items():
            if k.startswith("x-"):
                continue
            if k not in KNOWN:
                raise SystemExit(f"{where}: unsupported JSON Schema keyword {k!r} (extend scripts/gen_models.py deliberately)")
            if k in ("properties", "$defs"):
                for name, sub in v.items():
                    check_keywords(sub, f"{where}/{name}")
            elif k in ("items", "additionalProperties") and isinstance(v, dict):
                check_keywords(v, f"{where}/{k}")
            elif k in ("oneOf", "anyOf"):
                for i, sub in enumerate(v):
                    check_keywords(sub, f"{where}/{k}[{i}]")


def doc_en(node: dict) -> str | None:
    d = node.get("x-doc")
    if isinstance(d, dict) and d.get("en"):
        return d["en"]
    return node.get("description")


def pascal(s: str) -> str:
    return "".join(p[:1].upper() + p[1:] for p in s.replace("-", "_").split("_"))


def is_class(node: dict) -> bool:
    return node.get("type") == "object" and "properties" in node


# ------------------------------------------------------------------ Python (pydantic)
class PyGen:
    def __init__(self, name: str, schema: dict):
        self.name, self.schema = name, schema
        self.defs = schema.get("$defs", {})
        self.classes: list[tuple[str, dict]] = []
        self.aliases: list[tuple[str, str]] = []
        self.inline: dict[int, str] = {}

    def ref_name(self, ref: str) -> str:
        if not ref.startswith("#/$defs/"):
            raise SystemExit(f"{self.name}: only #/$defs refs are supported, got {ref}")
        return ref.split("/")[-1]

    def lit(self, v: Any) -> str:
        return repr(v)

    def constraints(self, node: dict, array_like: bool = False) -> dict[str, Any]:
        c: dict[str, Any] = {}
        for src, dst in (("minimum", "ge"), ("exclusiveMinimum", "gt"), ("maximum", "le"), ("exclusiveMaximum", "lt")):
            if src in node:
                c[dst] = node[src]
        if "minLength" in node:
            c["min_length"] = node["minLength"]
        if "minItems" in node:
            c["min_length"] = node["minItems"]
        if "maxItems" in node:
            c["max_length"] = node["maxItems"]
        if "minProperties" in node:
            c["min_length"] = node["minProperties"]
        return c

    def base_type(self, node: dict, hint: str) -> str:
        if "$ref" in node:
            return self.ref_name(node["$ref"])
        if "const" in node:
            return f"Literal[{self.lit(node['const'])}]"
        if "enum" in node:
            return "Literal[" + ", ".join(self.lit(v) for v in node["enum"]) + "]"
        for key in ("oneOf", "anyOf"):
            if key in node:
                return "Union[" + ", ".join(self.type_of(s, hint) for s in node[key]) + "]"
        t = node.get("type")
        if isinstance(t, list):
            return "Union[" + ", ".join(self.base_type({**node, "type": x}, hint) for x in t) + "]"
        if t == "string":
            return "str"
        if t == "number":
            return "float"
        if t == "integer":
            return "int"
        if t == "boolean":
            return "bool"
        if t == "null":
            return "None"
        if t == "array":
            return f"list[{self.type_of(node['items'], hint)}]"
        if t == "object":
            if is_class(node):
                cls = self.inline.get(id(node)) or pascal(hint)
                self.inline[id(node)] = cls
                self.classes.append((cls, node))
                return cls
            ap = node.get("additionalProperties", True)
            return f"dict[str, {self.type_of(ap, hint) if isinstance(ap, dict) else 'Any'}]"
        raise SystemExit(f"{self.name}: cannot map {node!r}")

    def type_of(self, node: dict, hint: str) -> str:
        base = self.base_type(node, hint)
        c = self.constraints(node)
        if c and node.get("type") not in (None,) and "$ref" not in node:
            args = ", ".join(f"{k}={v!r}" for k, v in c.items())
            return f"Annotated[{base}, Field({args})]"
        return base

    def field(self, key: str, node: dict, required: bool, owner: str) -> str:
        t = self.base_type(node, f"{owner}_{key}")
        kw = self.constraints(node)
        doc = doc_en(node)
        default: str | None = None
        if "default" in node:
            d = node["default"]
            if d == {} and "$ref" in node:
                default = f"default_factory={self.ref_name(node['$ref'])}"
            elif d == {} and node.get("type") == "object":
                default = "default_factory=dict"
            else:
                default = f"default={self.lit(d)}"
        elif not required:
            default = "default=None"
            if "None" not in t:
                t = f"Union[{t}, None]"
        args = ([default] if default else ["..."]) + [f"{k}={v!r}" for k, v in kw.items()]
        if doc:
            args.append(f"description={doc!r}")
        simple_default = default is not None and default.startswith("default=") and len(args) == 1
        if simple_default:
            return f"    {key}: {t} = {default[len('default='):]}"
        if not args[1:] and default == "...":
            return f"    {key}: {t}"
        return f"    {key}: {t} = Field({', '.join(args)})"

    def class_src(self, cls: str, node: dict) -> str:
        lines = [f"class {cls}(_Strict):" if node.get("additionalProperties") is False else f"class {cls}(BaseModel):"]
        d = doc_en(node)
        if d:
            lines.append(f'    """{d}"""')
            lines.append("")
        required = set(node.get("required", []))
        props = node["properties"]
        for key, sub in props.items():
            lines.append(self.field(key, sub, key in required, cls))
        if len(lines) == 1:
            lines.append("    pass")
        # JSON Schema allows an optional field to be absent but not null; the model type admits None only as the
        # "absent" default, so an explicit null must be rejected to agree with the schema.
        no_null = [k for k, sub in props.items() if k not in required and "default" not in sub and not self.nullable(sub)]
        if no_null and node.get("additionalProperties") is False:
            lines.insert(1 if not d else 3, "    __non_nullable__: ClassVar[tuple[str, ...]] = (" + "".join(f"{k!r}, " for k in no_null) + ")")
            lines.insert(2 if not d else 4, "")
        return "\n".join(lines)

    def nullable(self, node: dict) -> bool:
        t = node.get("type")
        return (isinstance(t, list) and "null" in t) or t == "null" or any(self.nullable(x) for k in ("oneOf", "anyOf") for x in node.get(k, []))

    def render(self) -> str:
        # definitions first (so refs resolve), then the root; aliases for non-object defs
        out_classes: list[str] = []
        aliases: list[str] = []
        order = list(self.defs.items())
        for name, node in order:
            if is_class(node):
                out_classes.append(self.class_src(name, node))
            else:
                aliases.append(f"{name} = {self.type_of(node, name)}")
        root_cls = self.schema["title"]
        out_classes.append(self.class_src(root_cls, self.schema))
        # inline classes discovered while rendering go before their users; emit all remaining ones first
        extra = [self.class_src(c, n) for c, n in self.classes]
        body = "\n\n\n".join(aliases and ["\n".join(aliases)] or [])
        parts = [p for p in (body, *extra, *out_classes) if p]
        needs = "\n".join(
            [
                "from __future__ import annotations",
                "",
                "from typing import Annotated, Any, ClassVar, Literal, Union",
                "",
                "from pydantic import BaseModel, ConfigDict, Field, model_validator",
            ]
        )
        return (
            f'"""{HEADER.format(name=self.name)}"""\n\n{needs}\n\n\n'
            "class _Strict(BaseModel):\n"
            "    model_config = ConfigDict(extra=\"forbid\")\n"
            "    __non_nullable__: ClassVar[tuple[str, ...]] = ()\n\n"
            "    @model_validator(mode=\"before\")\n"
            "    @classmethod\n"
            "    def _reject_explicit_null(cls, data: Any) -> Any:\n"
            "        if isinstance(data, dict):\n"
            "            for key in cls.__non_nullable__:\n"
            "                if key in data and data[key] is None:\n"
            "                    raise ValueError(f\"{key}: null is not allowed; omit the field instead\")\n"
            "        return data\n\n\n"
            + "\n\n\n".join(parts)
            + "\n"
        )


# ------------------------------------------------------------------ TypeScript
class TsGen:
    def __init__(self, name: str, schema: dict):
        self.name, self.schema = name, schema
        self.root = schema["title"]
        self.defs = schema.get("$defs", {})
        self.decls: list[str] = []

    def ref_name(self, ref: str) -> str:
        return self.root + ref.split("/")[-1]

    def comment(self, node: dict, indent: str = "") -> str:
        parts = []
        d = doc_en(node)
        if d:
            parts.append(d)
        extra = []
        if "x-unit" in node:
            extra.append(f"unit: {node['x-unit']}")
        if "default" in node and not isinstance(node["default"], (dict, list)):
            extra.append(f"default: {json.dumps(node['default'])}")
        if node.get("x-assumption"):
            extra.append("assumption")
        if extra:
            parts.append("(" + "; ".join(extra) + ")")
        if not parts:
            return ""
        return f"{indent}/** {' '.join(parts)} */\n"

    def type_of(self, node: dict, hint: str) -> str:
        if "$ref" in node:
            return self.ref_name(node["$ref"])
        if "const" in node:
            return json.dumps(node["const"])
        if "enum" in node:
            return " | ".join(json.dumps(v) for v in node["enum"])
        for key in ("oneOf", "anyOf"):
            if key in node:
                return " | ".join(self.type_of(s, hint) for s in node[key])
        t = node.get("type")
        if isinstance(t, list):
            return " | ".join(self.type_of({**node, "type": x}, hint) for x in t)
        if t == "string":
            return "string"
        if t in ("number", "integer"):
            return "number"
        if t == "boolean":
            return "boolean"
        if t == "null":
            return "null"
        if t == "array":
            inner = self.type_of(node["items"], hint)
            lo, hi = node.get("minItems"), node.get("maxItems")
            if lo is not None and lo == hi and lo <= 4:
                return "[" + ", ".join([inner] * lo) + "]"
            return f"{inner}[]" if "|" not in inner else f"({inner})[]"
        if t == "object":
            if is_class(node):
                name = self.root + pascal(hint)
                self.decls.append(self.interface(name, node))
                return name
            ap = node.get("additionalProperties", True)
            return f"Record<string, {self.type_of(ap, hint) if isinstance(ap, dict) else 'unknown'}>"
        raise SystemExit(f"{self.name}: cannot map {node!r}")

    def interface(self, name: str, node: dict) -> str:
        required = set(node.get("required", []))
        lines = []
        for key, sub in node["properties"].items():
            opt = "" if key in required else "?"
            lines.append(self.comment(sub, "\t") + f"\t{key}{opt}: {self.type_of(sub, key)};")
        return self.comment(node) + f"export interface {name} {{\n" + "\n".join(lines) + "\n}\n"

    def render(self) -> str:
        decls: list[str] = []
        for name, node in self.defs.items():
            tsname = self.root + name
            if is_class(node):
                decls.append(self.interface(tsname, node))
            else:
                decls.append(self.comment(node) + f"export type {tsname} = {self.type_of(node, name)};\n")
        root = self.interface(self.root, self.schema)
        nested = self.decls
        return f"// {HEADER.format(name=self.name)}\n\n" + "\n".join([*decls, *nested, root])


def outputs(schemas_dir: Path, py_out: Path, ts_out: Path) -> dict[Path, str]:
    res: dict[Path, str] = {}
    for name in SCHEMAS:
        schema = json.loads((schemas_dir / f"{name}.schema.json").read_text())
        check_keywords(schema, name)
        res[py_out / f"{name}.py"] = PyGen(name, schema).render()
        res[ts_out / f"{name}.ts"] = TsGen(name, schema).render()
    res[py_out / "__init__.py"] = '"""Models generated from schemas/*.schema.json (see scripts/gen_models.py)."""\n'
    return res


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--schemas", type=Path, default=ROOT / "schemas")
    ap.add_argument("--py-out", type=Path, default=ROOT / "packages/common/src/strandbeest_common/models")
    ap.add_argument("--ts-out", type=Path, default=ROOT / "packages/core/src/generated")
    args = ap.parse_args(argv)
    files = outputs(args.schemas, args.py_out, args.ts_out)
    stale = [p for p, text in files.items() if not p.exists() or p.read_text() != text]
    if args.check:
        # compare after the formatter the repo uses, so run formatting before --check when writing
        if stale:
            for p in stale:
                print(f"stale: {p.relative_to(ROOT) if p.is_relative_to(ROOT) else p}")
            print("generated files are out of date: run python scripts/gen_models.py && pnpm lint")
            return 1
        print(f"ok: {len(files)} generated files up to date")
        return 0
    for p, text in files.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
